### ISSUE TITLE
Missing text/link in The Placeholder Kitten form on Team page 

### ISSUE THREAD

**Issue by OlenaRogalska** [shescoding/shescoding-dot-org#101]
Missing test/link after words "go ahead and". 
![screen shot 2017-06-02 at 4 07 14 pm](https://cloud.githubusercontent.com/assets/28667320/26747882/bc60b932-47ad-11e7-846e-c58397982881.png)

**Comment by jadefaerie** [comment]
Fixed with check in https://github.com/shescoding/shescoding-dot-org/pull/115
