### ISSUE TITLE
Invalid links to LinkedIn profile on Team page.

### ISSUE THREAD

**Issue by OlenaRogalska** [shescoding/shescoding-dot-org#102]
Steps for reproduce: 
Click on "Mark S. Lee" image link.
Result: "Profile Not Found/Profile not available " message from LinkedIn website is displayed.
![screen shot 2017-06-02 at 4 18 19 pm](https://cloud.githubusercontent.com/assets/28667320/26748181/4d8a9b92-47b0-11e7-83a8-8e8754f7a41d.png)

Same step to reproduce and same result for "Robin Hauser Reynolds" image link.
![screen shot 2017-06-02 at 4 18 25 pm](https://cloud.githubusercontent.com/assets/28667320/26748192/5bedaf62-47b0-11e7-8172-bee095105d6d.png)

![screen shot 2017-06-02 at 4 27 41 pm](https://cloud.githubusercontent.com/assets/28667320/26748200/6e2d8a26-47b0-11e7-8ef3-061e79c1ecb2.png)

**Comment by cherchezlafemme** [comment]
Will be fixed with release of new updated Team page. Thank you for reporting the issue!

**Comment by cherchezlafemme** [comment]
Went to production on 10/15/2018.
