### ISSUE TITLE
Add a section with Testimonials to the front page.

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#122]
Add testimonials to the front page. This should appear below the Mentorship section.

Testimonial: consists of one picture, a paragraph of text, a name and title (to be taken from [http://techwomenrising.org/2018/assets/TWR2018-SponsorOptions.pdf](http://techwomenrising.org/2018/assets/TWR2018-SponsorOptions.pdf)).

Navigation: One testimonial should be visible at a time, with a small arrow on each side to scroll forward to the next or previous one.

**Comment by kellim** [comment]
Can I work on this one @natsteinmetz?

**Comment by cherchezlafemme** [comment]
@kellim yes please do!

**Comment by kellim** [comment]
Do we want the pictures of the person giving the testimonial from the pdf to be in it? If so, how can I get those pictures?

**Comment by natsteinmetz** [comment]
Yes, we do :) I'll post them to you on Slack, thanks for asking, @kellim

**Comment by kellim** [comment]
Can we make both testimonials the same size and put a link to "more"? 

The two testimonials being different sizes is presenting problems with the content under it shifting when switching between testimonials, and you can use JS to make the smaller one the size of the larger one, but it won't work responsively with the Bootstrap 3 carousel.

If that is ok, how about having the testimonial expand to show all the text when more is clicked, then the content below it would shift, but it wouldn't be every time you advanced to a new testimonial, just when expanding to read the whole thing.

**Comment by kellim** [comment]
I was able to get this to work without cutting testimonials off as limiting testimonials to a certain amount of characters wouldn't guarantee they are the same amount of lines and JS would still be needed.

**Comment by cherchezlafemme** [comment]
Merged to master on Dec 1 2018
