### ISSUE TITLE
Add Porsha Robinson to /team page as contributor

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#123]
Name: Porsha Robinson
Picture: attached
Title: Contributor
Bio: Porsha is a Software Engineer with a background in Computer Networking and Information Systems Security. Coding is her passion and she is an advocate for getting more women into STEM.

label: teamUpdate, small

assignee:

![porsha_robinson](https://user-images.githubusercontent.com/3076388/47467414-1feff880-d7ab-11e8-94b5-d240add24ade.png)

**Comment by marshallhelenm** [comment]
I'll work on this one.

**Comment by natsteinmetz** [comment]
Thanks, @marshallhelenm :)

**Comment by marshallhelenm** [comment]
I'm really sorry things came up and I am unable to complete this! Someone please change it back to open so that someone else can take care of it. Thanks for everything!

**Comment by cherchezlafemme** [comment]
No problem @marshallhelenm Thank you so much for letting us know!

**Comment by kellim** [comment]
Oops, I'd moved this by mistake so I moved it back.

**Comment by cherchezlafemme** [comment]
this update is part o PR https://github.com/shescoding/shescoding-dot-org/pull/166

**Comment by cherchezlafemme** [comment]
Merged to master 12/10/2018.
