### ISSUE TITLE
Upgrade to rails latest (currently 4.1.7, latest is 5.2.1)

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#128]
!!! dependent on Issue #127 !!!

- take a look at upgrade path
- check for version conflicts in dependencies
- if no serious problems, upgrade rails
- run tests and do manual regression test to make sure nothing is broken)
- update readme

**Comment by cherchezlafemme** [comment]
merged to master on 01/20/19
