### ISSUE TITLE
Add available volunteer positions section with descriptions to volunteers page.

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#133]
Use deck from slack with description and titles. Link to from volunteer page. Ask for the deck, please.

**Comment by adriennelim** [comment]
I'll try to work on this.

**Comment by natsteinmetz** [comment]
Ok, thanks @adriennelim :)

**Comment by cherchezlafemme** [comment]
no problem @adriennelim thank you so much for letting us know! ❤️

**Comment by ksmith10309** [comment]
I would like to work on this :)

**Comment by cherchezlafemme** [comment]
merged to master 01/20/19
