### ISSUE TITLE
"Tech Women Rising" conference link not visible unless hovered over

### ISSUE THREAD

**Issue by adriennelim** [shescoding/shescoding-dot-org#136]
**Describe the bug**
"Tech Women Rising" conference link in Volunteer page font color is white, which is the same as background color so not visible unless hovered over.

**To Reproduce**
1. Go to https://shescoding.org/volunteer
2. Look at 5th bullet point for Tech Women Rising conference
3. Hover over whitespace and see link in green font

**Expected behavior**
Font color to be in green 

**Screenshots**
![image](https://user-images.githubusercontent.com/40710985/47474785-838b1d80-d7cd-11e8-98bf-49b24de88446.png)

**Desktop (please complete the following information):**
 - Browser: chrome, safari, firefox

**Comment by adriennelim** [comment]
I'll work on fixing this.

**Comment by natsteinmetz** [comment]
Sounds good, thanks @adriennelim :)

**Comment by cherchezlafemme** [comment]
Merged to master on 10/27/2018
