### ISSUE TITLE
Add Aeone Singson to /team page

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#139]
Name: Aeone Singson
Picture: attached
LinkedIn URL: https://www.linkedin.com/in/aeone/
Title: Seattle Chapter Lead
Bio: Software engineer at Microsoft through the apprentice pathway. Very passionate about spreading technology and education access.

![aeone](https://user-images.githubusercontent.com/3076388/47536736-bb9a6b00-d876-11e8-81e8-2de0bbe799b0.jpeg)

**Comment by Elenaires** [comment]
I will work on this. :)

**Comment by cherchezlafemme** [comment]
@Elenaires left comments on PR: https://github.com/shescoding/shescoding-dot-org/pull/141 Your code looks good, we just need to make sure that your PR includes only the changes for this issue so that we can go ahead and bring them into master. Thank you!

**Comment by cherchezlafemme** [comment]
Merged to master on 10/27/2018
