### ISSUE TITLE
Add Kelli Blalock to /team page

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#140]
Name: Kelli Blalock
Picture: TBD
LinkedIn URL: https://www.linkedin.com/in/kelliblalock/
Title: Social Media & Contributor
Bio: TBD

**Comment by kellim** [comment]
Thanks, I'd like to do this one 😃

**Comment by natsteinmetz** [comment]
Go for it, @kellim 🙂

**Comment by cherchezlafemme** [comment]
merged to master Nov 30th.
