### ISSUE TITLE
Add jshint to the readme documentation.

### ISSUE THREAD

**Issue by cherchezlafemme** [shescoding/shescoding-dot-org#148]
Add information on how to run jshint locally. Add a note that any contributor that makes changes to javascript files or adds new, needs to run jshint.

To run linter:` bundle exec rake jshint`

Based on:
https://github.com/shescoding/shescoding-dot-org/pull/134
https://github.com/damian/jshint

**Comment by lena-pl** [comment]
https://github.com/shescoding/shescoding-dot-org/pull/154

**Comment by cherchezlafemme** [comment]
Merged to master on 10/29/2018.

**Comment by cherchezlafemme** [comment]
@lena-pl thank you for your help!
