### ISSUE TITLE
Inconsistent navbar height

### ISSUE THREAD

**Issue by Elenaires** [shescoding/shescoding-dot-org#153]
**Describe the bug**
When the screen size is between 758px to 849px, the navbar appears larger. 

**To Reproduce**
1. Go to https://shescoding.org
2. Resize the screen horizontally and watch the navbar height changes.

**Expected behavior**
navbar appears larger when screen size is at 768px to 849px (horizontally)

**Screenshots**
When screen size is between 768 - 849px
![picture1](https://user-images.githubusercontent.com/16939909/47623275-d239ff80-dacc-11e8-83ac-6256830f43f0.png)

Other screen size
![picture1](https://user-images.githubusercontent.com/16939909/47623292-feee1700-dacc-11e8-974e-1a9e11cd3624.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome, safari

**Comment by cherchezlafemme** [comment]
Verified, this is a bug. needs to be addressed. @Elenaires thank you for reporting!

**Comment by ckhung5** [comment]
@cherchezlafemme I fix it.. I will put a pull request :)

**Comment by cherchezlafemme** [comment]
Addressed by PR: https://github.com/shescoding/shescoding-dot-org/pull/158
Merged to master on 11/3/2018
thank you @ckhung5 for you help!
