### ISSUE TITLE
Reorder team members on /team page.

### ISSUE THREAD

**Issue by cherchezlafemme** [shescoding/shescoding-dot-org#161]
**Reorder the team members on https://shescoding.org/team
 page to show up in the following order:**
_(first row)_
Nathalie Steinmetz
Miki Hobgood
Anna Krupp
Brenda Stensland
_(second row)_
Aeone Singson
Patrizia Trammell
Liya Kurkov
You

**Comment by kellim** [comment]
@cherchezlafemme I'm adding myself to the /team page for issue #140, so can I do this issue at the same time and add myself last on the second row and then "You" would be by itself on the third row for now?

**Comment by cherchezlafemme** [comment]
@kellim that sounds great! can you also remove Patrizia Trammell? she is not longer in Tacoma so that info is outdated. So we can have on the team page:
(first row)
Nathalie Steinmetz
Miki Hobgood
Anna Krupp
Aeone Singson
(second row)
Brenda Stensland
Liya Kurkov
Kelli Blalock
You

**Comment by kellim** [comment]
Sure, happy to do so, thanks!
