### ISSUE TITLE
Stray a tag on front page

### ISSUE THREAD

**Issue by kellim** [shescoding/shescoding-dot-org#163]
There's a stray closing `</a>` tag on the site under the "What's New" section.

```
<li>Launching our
                Seattle Fall/Winter Code-a-thon</a>, which will run from November to January 2018.</li>
```

I'd be happy to fix this, or if someone is updating the What's New content soon they could fix it then.

**Comment by cherchezlafemme** [comment]
@kellim you can open a PR. just create a new feature branch of master so that we can merge it separately and open a PR to remove the not needed tag. Thank you!

**Comment by kellim** [comment]
Will do, thanks!
