### ISSUE TITLE
Links in "YOU?" tooltip on team page disappear in Firefox upon hovering

### ISSUE THREAD

**Issue by kellim** [shescoding/shescoding-dot-org#170]
**Describe the bug**

When viewing the team page with Firefox, links on the tooltips popup for the "You?" entry with the kitten image disappear when hovered over. (The kitten is the only "team member" with links in the tooltip)

**To Reproduce**

1. Go to http://shescoding.org/team using Firefox
2. Hover over image of kitten with "YOU?" under it
3. Hover over links within the tooltip that pops up and see if they disappear.

**Expected behavior**

When hovering over the links, they should stay visible and become underlined as they do in latest versions of Chrome and Edge.

**Screenshots**

![firefoxlinkbug](https://user-images.githubusercontent.com/2024584/49904242-729a7800-fe1e-11e8-815c-d6f002707412.gif)

**Desktop (please complete the following information):**

 - OS: Windows 10 & MacOS Sierra
 - Browser Firefox
 - Version 64.0 on Windows 10 & 61.0.2 on MacOS Sierra (versions tested, suspect most Firefox versions have the issue)

**Comment by kellim** [comment]
@cherchezlafemme I'd like to work on this issue I found and try to figure it out.

**Comment by kellim** [comment]
After submitting this issue, I also found another issue in Firefox only that seems related where if you double click (or sometimes just click once) on text within a tooltip for a team member, the line of text clicked on disappears. It seems like this could be related to the issue where links are disappearing upon hovering, but should a separate issue be created for this additional issue?

![firefoxtextdisappearingbug](https://user-images.githubusercontent.com/2024584/49905204-b8a50b00-fe21-11e8-9a4d-d738b36b0f2d.gif)

**Comment by cherchezlafemme** [comment]
@kellim thank you for reporting this! and yes, please, you can work on this issue :) we appreciate all you help!
