### ISSUE TITLE
Fix styling of hamburger dropdown in mobile view

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#27]
* links should appear underneath the hamburger icon
* there should be a box behind it, with a background, which will make the links better visible and not directly overlaid over the text & images of the content.

**Comment by tenchijayp** [comment]
It looks like the menu items are showing on page load, instead of the expected behavior of being hidden until the user taps on the hamburger button as well.

**Comment by natsteinmetz** [comment]
Fixed by #37
