### ISSUE TITLE
Transition between empty and full hearts fails (full hearts don't show up)

### ISSUE THREAD

**Issue by natsteinmetz** [shescoding/shescoding-dot-org#32]

**Comment by natsteinmetz** [comment]
@khjrtbrg Is this something you can fix until tomorrow evening?

**Comment by khjrtbrg** [comment]
I'll take a look!

**Comment by natsteinmetz** [comment]
Oh, you already saw it! I just mentioned it in my email ;) Thanks for having a look at it!

**Comment by khjrtbrg** [comment]
This should be fixed by [this PR](https://github.com/shescoding/shescoding-dot-org/pull/38).

**Comment by natsteinmetz** [comment]
@khjrtbrg It is fixed, yes. Well done! :)
