### ISSUE TITLE
footer text styling on mobile phone 

### ISSUE THREAD

**Issue by tenchijayp** [shescoding/shescoding-dot-org#34]
(enhancement)
Footer text for both portrait and landscape view on mobile phone looks awkward - attached screenshot below. Looks good on iPad but for mobile phone displays perhaps making the font smaller to fit two lines for portrait and one for landscape view would be better. 

![screenshot_2015-04-16-14-54-21](https://cloud.githubusercontent.com/assets/356679/7192283/ee543876-e448-11e4-96c8-bed59cc525e2.png)

**OS:** Android 5.1
**Browser:** Chrome (stock browser), FireFox, Dolphin browser (all latest builds)

**Comment by geoffstead** [comment]
I was about to add this one, and you got there first! It does look quite awkward. Agreed!

**Comment by jadefaerie** [comment]
Fixed!
