### ISSUE TITLE
Wrong location of popover display on mobile

### ISSUE THREAD

**Issue by tenchijayp** [shescoding/shescoding-dot-org#36]
Tapping on the images on Team page (of cute kittens for now) displays the popover text way below where it should be.  Works fine on Chrome on Win7, iOS Safari but same wrong behavior happens on Android browsers. 

**OS:** Android 5.1
**Browser:** Chrome (stock browser), FireFox, Dolphin browser (all latest builds)
**Page tested:** http://shescoding-wamuq6fved.elasticbeanstalk.com/team

**Comment by natsteinmetz** [comment]
@brigid2718 Is this something you could fix?

**Comment by geoffstead** [comment]
also in full chrome (not just the android stock browser)

**Comment by brigid2718** [comment]
Working on this now!

**Comment by natsteinmetz** [comment]
Fixed by #61 and #62.
