### ISSUE TITLE
Resources - alphabetical order

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#42]
It would be nice if the list was alphabetical as it would be easier for the eye to scroll down: http://shescoding-wamuq6fved.elasticbeanstalk.com/resources

Career Advancement
Diversity
Education
Gaming
Hiring
Kids
Leadership
Local
Mentorship
Negotiations
Networking
Online Classes
Podcasts/YouTube Channels
Research/White Papers
Sexism
Statistics
Workshops

**Comment by natsteinmetz** [comment]
Fixed in #67.
