### ISSUE TITLE
Need a better contrast

### ISSUE THREAD

**Issue by Videhi** [shescoding/shescoding-dot-org#46]
I like the idea of these boxes displaying the count down of days, but somehow - the contrast seems pretty weak and suddenly, it doesn't really distinguish with black background. 

Just a suggestion  - turn the boxes grey and turn the numbers black. 

![dates](https://cloud.githubusercontent.com/assets/11992207/7200576/3ecf80a0-e4f6-11e4-86ce-6de1ba6cc7bf.jpg)

**Comment by JessWakelin** [comment]
Great idea to promote the launch!
Maybe on the new site it could be a 'splash page' before going to the home page appears or have the countdown at the top of the page in the header?

even though its in two days :)

**Comment by natsteinmetz** [comment]
:D Sorry, I didn't think of doing anything like that. Might have been a good idea though...
