### ISSUE TITLE
Hidden Subscribe button

### ISSUE THREAD

**Issue by Videhi** [shescoding/shescoding-dot-org#48]
I notice that the Follow (subscribe) option is pushed to the far end corner of the page, and is barely visible. It will be helpful to make it a bit more visible.

Just a suggestion - you may bring it up on par with Like us, Follow us...
 
![subscribe](https://cloud.githubusercontent.com/assets/11992207/7200728/a13b9926-e4f7-11e4-9f81-355e808a19a0.jpg)

**Comment by natsteinmetz** [comment]
Thanks @Videhi for checking our site for bugs. This wordpress blog is as of now not reachable anymore, it has been replaced by the real site that is being launched tonight/tomorrow. Sorry this wasn't clearer before!
