### ISSUE TITLE
Contact us emails addresses

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#50]
I've read the text 'Want to learn more or be a part of the she’s coding team?'  - I made the decision to press Contact us. [[http://shescoding-wamuq6fved.elasticbeanstalk.com/how]]

When i press on Contact us on this page, it takes me to the Connect page. I then press Contact us via email: She's Coding and opens up my mail with nathalie@shescoding.org

two comments
1) I would make the contact us a link so i can email straight away
2) should it go to a nathalie@shescoding.org or info@shescoding.org

**Comment by natsteinmetz** [comment]
This has been updated in the meanwhile, it still goes to the 'Connect' page, but the email address there is info@shescoding.org. The goal is to have a form on the 'Connect' page instead of the email - this is still in implementation, but will be updated soon.
