### ISSUE TITLE
iPad mini: footer on Connect page

### ISSUE THREAD

**Issue by JessWakelin** [shescoding/shescoding-dot-org#54]
Is there a way to ensure the footer is based at the bottom?

On the others pages there's more content and so the footer appears at the bottom
![ipad_minicopy](https://cloud.githubusercontent.com/assets/11992232/7201902/9f115d22-e504-11e4-8d6f-e0e4ee6b4e9c.jpg)

(sorry i was having issues taking a screenshot from the ipad - took photo using phone)

**Comment by cherchezlafemme** [comment]
merged to master on 11/1/18
