### ISSUE TITLE
Samsung S4 - Unaligned elements

### ISSUE THREAD

**Issue by Videhi** [shescoding/shescoding-dot-org#55]
On the home screen, the elements towards the very bottom don't seem aligned to me. It may be a good idea to left or center align the 2nd and 3rd lines. 

![screenshot_2015-04-17-13-11-21](https://cloud.githubusercontent.com/assets/11992207/7201908/bcd8595a-e504-11e4-8f1f-9684b280e995.png)

**Comment by natsteinmetz** [comment]
Duplicate of #34
