### ISSUE TITLE
Samsung S4 - Links don't open a new page

### ISSUE THREAD

**Issue by Videhi** [shescoding/shescoding-dot-org#56]
http://shescoding-wamuq6fved.elasticbeanstalk.com/how 

None of the highlighted links open a new window/page. It can get tedious to keep tapping back to get back to home screen. 

![screenshot_2015-04-17-13-14-01](https://cloud.githubusercontent.com/assets/11992207/7201936/344dc808-e505-11e4-86b6-bc24ccb6ed1c.png)

**Comment by natsteinmetz** [comment]
Fixed by #65
