### ISSUE TITLE
Home page too wide for mobile chrome (HTC One)

### ISSUE THREAD

**Issue by geoffstead** [shescoding/shescoding-dot-org#60]
Only on the home page, the width is too wide. See menu button. The page can be slid a few pixels left and right. (Chrome on HTC One. Not in stock browser. that looks fine)
![image](https://cloud.githubusercontent.com/assets/2299032/7205307/42081cd2-e4dd-11e4-90fc-63dbcf7d91e3.png)

**Comment by jadefaerie** [comment]
Home page revamped!
